version: '3'

services:
  nginx:
    container_name: "hypertest-nginx"
    build:
      context: docker/nginx
      args:
        NGINX_DIR: conf.d
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - static:/var/static
      - ./media:/var/media
      - ./log/nginx:/var/log/nginx
      - ./ssl:/etc/ssl
      - ./front/build:/etc/nginx/html
    restart: on-failure
    depends_on:
      - back
    links:
      - back

  db:
    container_name: "hypertest-db"
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=hypertest
      - POSTGRES_USER=hypertest
      - POSTGRES_PASSWORD=hypertest
      - PGPASSWORD=hypertest
    ports:
      - "5432:5432"
    volumes:
      - ./var/pg_data:/var/lib/postgresql/data

  back:
    container_name: "hypertest-back"
    build: .
    volumes:
      - ./src:/code/src
      - static:/code/static
      - ./media:/code/media
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  swagger:
    container_name: "hypertest-swagger"
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - "./docs/swagger.yaml:/index.yaml"
    environment:
      SWAGGER_JSON: /index.yaml


volumes:
  static:
