version: '3'

services:
  nginx:
    build:
      context: docker/nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - static:/var/static
      - ./media:/var/media
      - ./log/nginx:/var/log/nginx
      - ./ssl:/etc/ssl
      - ./front/build:/etc/nginx/html
    restart: on-failure
    depends_on:
      - back
    links:
      - back

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=hypertest
      - POSTGRES_USER=hypertest
      - POSTGRES_PASSWORD=hypertest
      - PGPASSWORD=hypertest
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  back:
    build: .
    volumes:
      - ./src:/code/src
      - static:/code/static
      - ./media:/code/media
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  static:
